// This file is autogenerated by Flutter Tool. Do not edit.

import 'package:flutter_web_plugins/flutter_web_plugins.dart';

// ignore: public_member_api_docs
void registerPlugins(PluginRegistry registry) {
  // ignore: unnecessary_cast
  registry.registerMessageHandler();
}
